services:

  postgis:
    image: postgis/postgis:15-3.3
    container_name: georisk_postgis
    environment:
      POSTGRES_DB: georisk
      POSTGRES_USER: georisk_user
      POSTGRES_PASSWORD: georisk2019
    ports:
      - "5433:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d   # 01_create_tables.sql + 02_add_poi_tables.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U georisk_user -d georisk"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: georisk_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: modou.khabane.mbaye@usherbrooke.ca
      PGADMIN_DEFAULT_PASSWORD: georisk2019
    ports:
      - "5050:80"
    depends_on:
      - postgis
    restart: unless-stopped

  web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    container_name: georisk_web
    environment:
      POSTGRES_DB: georisk
      POSTGRES_USER: georisk_user
      POSTGRES_PASSWORD: georisk2019
      POSTGRES_HOST: postgis
      POSTGRES_PORT: "5432"
      DJANGO_SECRET_KEY: "prod-change-me-geocharge-montreal-2026"
    ports:
      - "8000:8000"
    depends_on:
      postgis:
        condition: service_healthy
    volumes:
      - ./src/web:/app
    restart: unless-stopped

volumes:
  postgis_data:
